var codeLangs = ["cpp", "py", "web", "cs", "java", "php", "rb"];
var codeColumns = ["language", "title", "id", "upvotes"];
var codeList = [[2, "Cipher Analyzer (Vigen\u00e8re/Caesar/Shift/Vigenere)", "W85GKwfubQ6Z", 20],
[1, "UUencode / UUdecode (newsgroups, email)", "cZHP5hh1tXe0", 2],
[1, "readline vs readlines (Q&A)", "c4k4yGg1qXUj", 3],
[2, "StarWars Imperial March [audio ~ haptic sync]", "Wfzu19163vr8", 4],
[2, "Ball overlay split animation [worker]", "Wm9FGmaEs1Ao", 10],
[2, "Check AnimationFrame rate bug", "WWrsjH8Fap4d", 17],
[2, "Image-event-driven photo scan, calendar picker", "WbYSrWcbJmh3", 2],
[2, "Modulo bias in PRNG [PoC; cleaning up]", "WmOmcQ9HYcDR", 7],
[2, "YouTube player API (rotated)", "WY2xou48ucG4", 17],
[1, "Egyptian multiply trick : How computers do it", "cchLO12ThqQz", 5],
[1, "List SoloLearn modules (updated)", "c071JeXy6LcW", 22],
[1, "New matrix multiply operator @ vs .dot()", "cjmj125VOeWl", 8],
[2, "NaN 'gotcha'", "WhXdhJ4RkZGY", 9],
[2, "'Let' vs 'var' : fix for transitional (JS/ES6)", "Wc4H6Np7vx8S", 10],
[0, "Pythonic string repeat (operator*)", "cWHLe1Mj1f18", 8],
[1, "Divide numbers by looping", "c8zv1uYcc0iV", 4],
[2, "float64 / double (Internals)", "WYCTOysAGnLv", 35],
[2, "Secret challenge answer validator [standalone]", "Wh2cLXgROesk", 3],
[2, "Secure passwords + Secret challenge answer validator", "Wz332N726f9Q", 2],
[1, "Euclidian distance via collections:Counter", "cbFZvXeHSs0B", 6],
[2, "The Sun...now-ish [all satellite sensors]", "WOdY9NmHfU14", 24],
[1, "A Python \"program\" program", "c60MO6n3DaiW", 5],
[2, "Canvas: resize \"zoom\" (CSS vs HTML dimensions)", "WETCkRaPNVhy", 23],
[1, "Numpy vs Python speed (works; +better)", "cp9uAJGsR3l3", 12],
[1, "Event tracing : call(), return, line, etc.", "cklgpC883uCT", 4],
[1, "Garbage collector infos", "cVG9zVeRGd3N", 10],
[2, "Zap 0's \"no test\" trick (Array.from() fix) [challenge]", "W1ffgsxzgIUo", 3],
[0, "\".   \" vs '.   ' (integer byte order)", "c3cS3hJbHs0i", 3],
[1, "IPv4: validate by behaviors, not plain values", "cd03CF9McF30", 4],
[5, "Working POST demo", "wubNMMMp8mYA", 15],
[1, "'Maze run' (saves state!) [v0.1 alpha]", "cx84c2P4zMgt", 9],
[2, "Scatterplot [WebGL]", "WkOjxnISn6m8", 15],
[1, "Image detection (library demo only)", "c8XXjWUgw2I7", 5],
[2, "FAST background threads (no imports)", "WsDgqurTNvRJ", 10],
[2, "Runaway regex: catastrophic backtracking (safe threads)", "WO38mvLryQ3Q", 4],
[2, "Background thread messaging", "WDvXcDNFofPk", 1],
[2, "Rnd color noise + accelerator datatype", "WBp7kFYTlyac", 8],
[2, "Sensors live streams [ acceleration gravity rotation ]", "WanUHKGqxs5r", 13],
[2, "Strobe light (v1)", "W0CRkJnZv5jq", 15],
[2, "Local storage - works [IndexedDB PoC]", "WfsYwC9tb8hB", 3],
[2, "BCD clock (now with ms)", "W9cfvIzP6T91", 7],
[2, "Image loader object [sdcard to canvas]", "W1XYEpVLlhjM", 1],
[1, "Random generates pi + video", "c6WmHJ82s1Y2", 3],
[2, "class inheritence: svg path injection", "WKLubPzanpv8", 5],
[0, "Single precision : digit 8 microscope", "c26j9deIV9DC", 3],
[0, "Hello World [obscure]", "cXQkq9TeESol", 11],
[1, "\u00a3 symbol encoding", "c6NQFsmNHz82", 7],
[2, "yin-yang - 1 div / no js", "WLZFqkui99gM", 29],
[2, "CSS custom props: $x vs. var(--x)", "WO1W556dRmXw", 3],
[2, "Browser/DOM inspector", "WVxar9XmY1N4", 19],
[2, "vibrate() now requires user intervention", "WNcw9wVoFc41", 10],
[0, "Add without + (use printf wisely)", "cF4BZHASZmtA", 4],
[2, "iframe postMessage + error cancel (works)", "WQ65OWBk2Rl0", 1],
[1, "Disallowed operators (6 alt ways) [challenge]", "c0laSyLWCgTL", 6],
[1, "bytecode + disassembly info [Python]", "cxYMW29npKWp", 3],
[1, "Single-hop flights, verbose [challenge]", "cJaPjtDUDS1E", 7],
[1, "Single-hop flights, 1-liner [challenge]", "cp6mWaNPY7ZI", 2],
[2, "Rolling Shutter Effect + extras", "W7c587W0ODxf", 30],
[2, "Dark Knight/Batpod (Shepard Tone Illusion) [Audio]", "W7jLtnVBmTyo", 27],
[0, "SoloLearn compile number (in-memory)", "cRzqbfwyP2rJ", 3],
[1, "Server identifier + roughly unique detail", "c7IUMJI0Ute2", 12],
[1, "Identify server (1 liners)", "c134OOV3wCzc", 2],
[2, "Word cloud for RFC-1945:HTTP", "W8rSJq3wQ3kn", 7],
[2, "regl triangle (fix: old webviews) [OpenGL]", "Wcw9kppQxRid", 17],
[1, "this...is a joke", "cV31QM0B0ozB", 15],
[0, "Quarks: pair/triple/quads : parallel bitcount + assembly msb [challenge]", "cpogCPP6rG33", 8],
[0, "Quarks [algorithm source] : Parallel bitcount + assembly MSB [challenge]", "cZX2I8giW2zV", 10],
[2, "SoloLearn logo imagemap [shows debug]", "WBJ8lS8yMplX", 15],
[0, "Why is this printing... (detail)", "crkEJL64XKLG", 4],
[1, "Native text color: no ANSI required", "c3QbcL54mfAG", 7],
[1, "Matrix ring rotate [HackerRank]", "chl9xOMCE1I7", 4],
[2, "Image embedded in HTML (no download)", "W9yG8qZkeF7T", 20],
[0, "Unusual termination : thrown exception [Q&A]", "c3PWTzjHcHm2", 4],
[0, "strfuncs 1-liner challenge [strcpy, strcmp, strcat -> memcpy, memcmp, ternary]", "cwQei2nPiQsL", 7],
[1, "~Rotate challenge [4-line \"utility\" demo]", "clf9WfPNSB48", 4],
[0, "Files gotcha (EOF flag vs ASCII 26)", "cyt3z1m2z69Q", 6],
[1, "Gameloop with Pythonic quit", "cAP6JETxuE4r", 8],
[1, "(is vs ==) using memory address", "cz4Pe3g9zJ7X", 10],
[1, "Largest file/edge crash tests (seek, close)", "cV414bDIoEE6", 6],
[2, "Which <li> clicked (from <ol>)", "WM1VQSFtBaFp", 4],
[0, "Newlines faster than << endl", "cRjbtysU5r3o", 14],
[2, "Waveforms, nodes, analyzer [audio demo]", "WtQNPJWBm54i", 6],
[2, "Battery info", "WM633Cfn7I69", 6],
[2, "phpinfo (ok; no TLE or Playground bug)", "W2yyJJHcKxWm", 5],
[0, "anoneon-Q&A related", "cFt8yu3krN5R", 4],
[0, "SoloLearn c++ version", "cu8tmoP4h80H", 15],
[2, "ident clicked button - this & custom data values - 4Q", "Wy0LUvUwBB22", 6],
[5, "phpinfo piece extractor", "wD65hMQ941SW", 4],
[3, "Predict Random (Microsoft .NET)", "c2UZ8pn0oZPz", 12],
[1, "Dump random memory", "cCyWhRHgLF0F", 11],
[2, "Function/Boolean statics (no vars)", "WN2CtG7CV16j", 5],
[2, "An ideal computing task (data entry -> added value)", "W6EtG9oqwvCE", 5],
[1, "Function overloading", "c9kVXZ5B9Ex2", 6],
[1, "Is workstation locked?", "cDvT2p7o5XHh", 3],
[0, "Text graph for sin()", "cd2CVa39kBFw", 14],
[0, "Text graph for circle (calculated)", "cFAi8v2r9Nd6", 9],
[1, "HTTP / CORS check (HEAD/OPTIONS/GET) for question", "choOE8kwZEmk", 6],
[2, "Morse [audio demo]", "WhA0089E477F", 4],
[2, "Wooo! [audio demo]", "W4v2mptfMYmk", 10],
[0, "c++ (vs Python) mod behavior with negs", "c0VcyWYMEfed", 11],
[1, "Python (vs c++) mod behavior with negs", "c7o8hur596jS", 9],
[1, "scan for \"remove\" (4Q)", "clwcMjR778n5", 3],
[1, "Open sockets, pids, ports, state", "cubR5whB2dZ1", 7],
[1, "Fibonacci -> phi (golden ratio)", "cZA6QHq1wxou", 12],
[1, "Happy birthday fly-in", "cfRg3yX3gjwR", 10],
[2, "Something different [jsf*]", "Wo4ysbH3jwcn", 7],
[0, "[challenge] getMin O(1) : \u00b1 stack [update]", "cTbsrlLgcN9n", 7],
[2, "[ES6] Sensors live streams [ acceleration gravity rotation ]", "WbKt65eY3gs2", 8],
[2, "Simple inheritence: 2d->3d coords", "WsU5B3cugn7C", 5],
[2, "Colorful Area Rug (2D rotation)", "WeD644osWWvu", 17],
[2, "CaptureTheFlag 3 [HackerRank]", "WqO3Bnm9rDnC", 3],
[2, "CaptureTheFlag 2 [HackerRank]", "WU7FVfemApZM", 1],
[2, "rotates?", "WEauRsC911SG", 6],
[2, "Countdown - no js counter", "WaR5C61vBLDg", 9],
[2, "peerJS companion iframe", "WSx7XZfWLdN9", 2],
[2, "fn.length, finally weirdness", "WZ9SV3dSLbdO", 1],
[1, "Print up to 512KB; no time limit exceeded", "cS6ycqbpkpL8", 13],
[4, "thread sleep time precision", "cDNk1eUpCv12", 0],
[2, "Mutation-Fired 'Firefly' Text", "WHpWYpR5FWwi", 19],
[0, "funny/odd", "c8qW69G5u7Ha", 2],
[2, "hr breaks align nesting", "W9f5UerHhvKR", 0],
[2, "debugging", "WdaD6YblGt8u", 0],
[2, "mathbox 2", "WUXy7idNPpdc", 1],
[0, "int_literal[ptr] (Silly c++ Tricks)", "c12ZF4d3Pq0y", 12],
[2, "Trendlines: random + averages", "WA2TQBOHm0hz", 6],
[1, "recursive \"in\", neat short-circuit (4Q)", "c9xsVsQilIbL", 4],
[0, "[challenge] getMin O(1) : + stack only", "co5umytGHG33", 6],
[0, "[challenge] getMin O(1) : \u00b1 stack", "cHv7Kq9AYJ9s", 7],
[2, "Hello Ring:no iframe + source [VPython]", "WtPnzZ4tFvUN", 10],
[2, "[Python Web] Interactive Input", "W1ytcdJlyPI7", 14],
[2, "Your LAN IP address is...", "WV02EpP6Fp7n", 4],
[2, "Quick event dump (swipe) [bugfix]", "WJveUSCzVZid", 8],
[0, "c++ assembly (add + multiply) [asm]", "c2XovH84x6DQ", 10],
[2, "Disable/null console (short/silent + longer/demo versions)", "WLxYacmLKBMI", 11],
[2, "Internet Relay Chat (irc)", "WeN0W6xcgi3e", 12],
[1, "Comms: stuffing keyboard", "cTIIViAIheMK", 8],
[2, "Speed Reader", "W6nybHh1bGHX", 19],
[2, "Async csv download (promises; manual start)", "Wq4SvyF5GPjd", 12],
[0, "Using gets() + stack canary [fixed a crash]", "clrkpx6TfU3S", 4],
[1, "Read CSV, load database, query  (CA real estate)", "clfBfGjZy384", 10],
[4, "CharGen PRNG stats [oddeofreq 4QA]", "cfcWVOC88168", 3],
[1, "Operator + str override (a couple Classes)", "c3w3XErsSzVT", 7],
[6, "ruby object id's (references)", "cbYnENB5Gh3u", 5],
[2, "SVG test suite (275 tests)", "WzEgoOXZ7fo4", 7],
[1, "Speech recognition demo (PocketSphinx)", "c2f82jygtyK6", 8],
[2, "Tupper's Self-Referential Formula", "Wd1YzYy3KVbT", 6],
[2, "alert() intercept / override", "WdS6lMQPli6D", 7],
[1, "Read audio file + stats (live demo: AIFF)", "c1AHY6gxx8r7", 9],
[1, "Launch Android Intent (usage statistics)", "cc7z80zZpkQi", 7],
[2, "Hello Ring:iframe + IDE [3D / VPython]", "W0ylF4Cfp6K1", 6],
[2, "[Python Web] Turtle", "WTj6PC3737Cd", 8],
[2, "4q-\"What's the difference?\" [form vars]", "Wm5KbGCQ49C3", 6],
[2, "Counting w/CSS (+ pseudos + attr extraction)", "WeJGJ90zAZUW", 14],
[1, "Interactive input source", "c7Tn0gQiLKd8", 6],
[1, "Everything's an object (+Java compare)", "cDzHTj3A5dO6", 7],
[2, "[Python Web] ANSI color XOR Cycle Map", "WRSLH8ZxPmDw", 6],
[5, "Calendar; first day calc + localization", "w3Sql6AuxTgS", 15],
[1, "XOR flip/fold cycle map (condensed)", "c6cJ0KHmoxJt", 6],
[0, "Uninitialized array after new()", "cS6k3oZL1474", 9],
[0, "Elements used, alt. magic number (fill_n or memset)", "cwifJUbLVM79", 6],
[1, "Top 9-word in RFC1945 (challenge)", "cax3xik2u9za", 11],
[2, "GL Solar System (ported Mathbox demo)", "W3mhtF3DP9kx", 5],
[1, "Optimize side-channel (challenge)", "c9oezEh8G1P7", 5],
[2, "Shadow DOM (Web components)", "W6y9t01OWtV8", 11],
[2, "Swipe up/down to... (reload not for app)", "WuFMCeNCxzyC", 9],
[2, "4Q: fn(y){y+1}(++a)+a+a", "WxTEI1rejx0I", 7],
[2, "Template literals [ES6 demo]", "WFeRYNB73QfO", 10],
[2, "CubeRoot (by Long Division)", "WT4eswl8Pto3", 7],
[2, "Plasma (older webviews fix) [OpenGL]", "WTf01GbxiNsY", 9],
[2, "Benchmark your mobile", "WwgDLry998CU", 8],
[2, "(US ONLY) Monopoly rare/semi-rare fast code checker", "W5a9gK84I347", 9],
[2, "Plasma (for updated WebViews) [OpenGL]", "WXo4dZV4H087", 11],
[1, "Adversarial password validator", "c423nlPbnm3E", 10],
[1, "IPv4 extended validator", "c4KPcxWDu9Lv", 9],
[2, "Filling \u24bb\u24de\u24dd\u24e3 background", "WPXKEfdAiDcB", 11],
[2, "js 'generator' : fib() [0 fix+unsafe]", "W0izfx5FISNx", 12],
[1, "\"while True\" async breakout (throw up a timer)", "cOKRiZ9ntR6P", 8],
[1, "FTP demo - e.g., old games (idSoftware)", "cncnN1Jzb7tB", 7],
[1, "isAlt challenge: Binary Cheater", "cCn9v5CQ6T6w", 10],
[1, "isAlt challenge: Validator Flipper", "cz2wjbzC74OH", 7],
[2, "4Q: Why is output 'two'?", "WJ1ug2oH5H24", 7],
[2, "3D function view [WebGL]", "W0jzXMT5qIp0", 24],
[2, "Tap ellipse/force visualizer", "W0jWAJfDQwds", 6],
[2, "SnakeCase challenge (RegEx)", "WI4sWMbGRXCY", 9],
[2, "HexdumpCanvas", "W45UvIrmR6fA", 1],
[2, "HexdumpPRE", "WjeiNyQtB2dW", 1],
[2, "hexdumpHTML", "WbQGgDKobCk3", 1],
[2, "upside down text", "Wwo1pg8g963m", 1],
[2, "Plug-n-Play Popup Error Console [demo]", "WWKt0cidbM9p", 11],
[2, "Plug-n-Play Popup Error Console [blank template]", "W6Y6tS3NcXRS", 7],
[2, "Javascript ErrConsole NEW/Easy", "WkUnKUuuYYpT", 11],
[0, "decimal fraction -> any base (2 to 255)", "cIC8qOLAfL7m", 9],
[0, "100! precision-loss weak detector", "c11kVGy5Jn2C", 13],
[0, "0.21745... to binary decimal and back", "cFi7bF4UQeCZ", 7],
[0, "100! doesn't fit in a double", "cmNS1d2qi84I", 13],
[1, "Kuba did it better (for Ahri Fox)", "cL1DOm8zF6rS", 12],
[1, "Where's the var? (Silly Python Tricks)", "ciUQKNVndgT2", 7],
[1, "Buffer swap split (Silly Python Tricks) ", "c35s1N5Rwzth", 13],
[1, "Printless print (Silly Python Tricks)", "ctuNdG44xznf", 12],
[1, "Network interface MAC address (continues: starmap, zip)", "cJX6G9yk4PL8", 7],
[1, "Iterator trick (starmap + zip clustering)", "cgWXLHDhmmuv", 11],
[1, "Five ways to sum + performance timers", "cyIBmuriM6Pm", 11],
[1, "4Q: Nested List Challenge (Lium Goon)", "cQLNDGdWp03U", 0],
[2, "Peer to peer: works, with notes (PoC)", "WDN9qBzViaaW", 9],
[2, "crypto", "Wyi04xQqi82d", 0],
[2, "emodjinn", "WctO2A8JIbDP", 0],
[2, "Date -> day of week (KeyValue method)", "WvFZGMOFc7Ep", 9],
[1, "Double-ended queues (deques/stacks)", "cPsjXNwjTyQY", 12],
[0, "packed struct", "cn8NYYi2zNM9", 0],
[2, "crashy", "WNAQpetEtPCq", 1],
[2, "4J.G. - why negative", "WhgTsGPsT731", 0],
[3, "persistent value for jalisa abdulgani dalvi", "csj5MbNno3u9", 0],
[2, "calendar", "W2EmhWDXZ5Y6", 5],
[2, "css fiddling", "WHy9Wl4h8BHe", 0],
[2, "4?: Animation crashes SLPG", "WJ7VcHpmEVFy", 0],
[4, "Sleep precision", "c2vtgDzZDic8", 0],
[1, "Spin", "c5fyMsA4H7nq", 12],
[0, "Float/Double precision demo", "ckZEfBRiUrEA", 12],
[1, "mazegen-charfiddle", "cLT01bVLrb2D", 0],
[2, "Small/quick generator example", "WAseetwBFbF0", 12],
[2, "LoopPerformanceTests (a weird check)", "WJ3o9sesqvpq", 0],
[1, "Various sys(datas)", "cyiK9SCytu46", 0],
[2, "js 'iterable' : fib()", "W8OboCWVb1ne", 9],
[0, "floats/doubles/ints", "cvBCZub42V75", 0],
[2, "Truly random (not a PRNG)", "WxkraG1imWtm", 11],
[2, "fetch - replaces XHR/XMLHttpRequest", "WWB9eLU9rcxG", 12],
[2, "CSS \"Adjacent Sibling\" selector", "WO2k5ED9EAuD", 14],
[0, "ASCII lines", "c51fBhYj1dc1", 1],
[2, "Javascript timer resolution", "WT5kJzI2HD19", 9],
[4, "kernel timer granularity (15.6 ms)", "czP9jC2cdJA8", 8],
[2, "HBFeedback", "Wkh5svUT6sb0", 1],
[1, "Hello <-(?)->  (in-memory gunzip)", "cpl25LvQ3wvu", 12],
[5, "Work/output: Thinking \"server vs. client\"", "wcvX7HlgPpmw", 12],
[1, "Memory available to Python (Win32 API)", "cKVeedVg6sZV", 16],
[2, "Blurry vs. sharp line (canvas)", "WQWeX3Q2X4lk", 10],
[1, "gzip-noiostring", "ct1UIx4p29s7", 0],
[2, "Imported Open Font + Quote", "WBAfs94Il8C6", 19],
[1, "'Maze run' generator (ported)", "c5ls8lG3SrjT", 9],
[2, "Character dump: HTML-entity-type", "W6hxkQ5V4I70", 9],
[0, "Hardware byte order (integers)", "cK0y1U1yOuBL", 7],
[0, "neat-why doesn't it add up correctly?", "c3OLq00dmRK1", 0],
[0, "Mysterious printf [SOLVED]", "cAmf8B5A36vQ", 7],
[1, "Py: Persistent data SoloLearn (sheets db)", "cJTcw0o5WgaZ", 7],
[1, "Py: Persistent data HOME version (simpler!)", "c37XERvwb2Cz", 6],
[1, "pers-wk", "cV9L5P7R1UdJ", 0],
[1, "wth2-2?", "c9UAqPE32yEy", 1],
[0, "nobug", "cfZmnhQ3Z2AQ", 0],
[1, "wth?", "cPNwx1omhpEg", 0],
[1, "reverse", "c91FelIvpdb2", 0],
[2, "unicode cookie", "WmiEIgGAc0V1", 0],
[0, "WeirdCode: Duff'sDevice", "cT46etCvzTbO", 8],
[1, "Python reference counts", "ct7ToIVRI24y", 8],
[1, "Cute True==1", "ciix0GnoyPQB", 0],
[2, "SFOpenData Demo-broken", "WrD0aV0FBMlh", 0],
[1, "[Time Trial] for Kuba Siekierzy\u0144ski's Magic square verificators", "c71MXSPI5ItS", 9],
[1, "Python + sqlite3 (works here)", "co2vRwg7GoEG", 12],
[1, "Multiprocessing (4 threads) in 6 codelines", "cPyfXZGRo5sr", 10],
[1, "straight *7 vs shift", "c7DlSTybttRN", 7],
[1, "ahri_timer", "cRS9ZNMg23Qd", 0],
[1, "python_server_memory", "c4IAoC6q2Rgz", 0],
[2, "Practice SQL (browser or app)", "WUg6o4QaxPGU", 20],
[0, "tricky", "cJaB2Mdm3w88", 0],
[1, "eval-custom", "cs8mcU7ULtnf", 0],
[4, "nudu", "c40CS1fkzWXR", 0],
[2, "hw", "W243799O3XNQ", 0],
[2, "setinterval test", "W7seqs6ott0k", 0],
[2, "vididd", "W6sZY4q0dwn6", 0],
[0, "try2", "ct7t2MEt1V11", 0],
[1, "md5seed_fiddling", "c00I5n5H4sq1", 0],
[1, "cplx0", "c9AgDuB81B6l", 0],
[1, "Goodstein sequence", "cG7lp29a4cwM", 8],
[0, "print5K", "cmaDqnBvfGfq", 0],
[2, "JS Error Console (OLD version snippet)", "WnfK9ry02dkS", 12],
[2, "JS Error Console", "WvxU8sN45K0M", 0],
[0, "Overflow", "cOoR4b8wTbiO", 7],
[2, "JS Error Console (1 line)", "Wf6hORNQ5IaQ", 2],
[1, "Reverse : recursive ternary abuse", "cL1DSxpItkBp", 8],
[1, "[shorter fork] Print your name in Symbols v1.6:fork [Bogdan Bogdanov]", "cGT47SJ5W534", 11],
[1, "Converter for Bogdon Bogdanov's \"Print your name in Symbols v1.6\"", "cJXX2A3gipAt", 10],
[0, "malloc() magnitude test", "cqOr4ND9XftZ", 10],
[2, "Javascript selfie (NO PERMS-Sample ONLY)", "WkXwFzo6Fw3N", 12],
[2, "HTML5 (555 tests) inlined", "WeBKGPjY0UHK", 15],
[2, "HTML5 File stuff checks", "WDATDt9GuboU", 0],
[2, "HTML5 File API check", "WXB3P1v6DUdY", 10],
[2, "bounce_line - beta 1.3", "W7D9bS0Fz2co", 18],
[2, "HTML5 local storage check", "WlEab312L9WR", 11],
[2, "SQL in-browser", "WNdUCjzyeFFJ", 17],
[2, "voxel test [WebGL]", "WJpHUkKuPkln", 11],
[2, "quiz", "WwkNOO8YlCxf", 0],
[2, "mathbox - label", "Wl9I6uL2759s", 1],
[2, "mathbox water", "WNDYY3oxeA1O", 0],
[2, "mathbox - solar system", "WXEsWisZ5OYe", 0],
[2, "mathbox colorcube", "W1T6dhbxk31u", 1],
[2, "mathbox 1", "WeW2869as502", 0],
[2, "bounce_line - beta 1.1", "WHMTMQeP8RL1", 6],
[2, "cssdeck forum answer", "Wz71RpT00D4B", 16],
[2, "Browse/Search SoloLearn website inside the app", "W3m5Kj2C7FUy", 12],
[1, "Dif between global/local", "c5a3zTNVrnyW", 13]];
